SELECT
R.COD_CAMPAIGN,
R.COD_KPI,
L2.LITERAL AS CHR_KPI_GR,
L1.LITERAL AS CHR_KPI_ENG,
L1.CATEG_NUM
FROM CM_REPDEF_COLUMNS_IQ AS R
LEFT OUTER JOIN CM_LITERALS_IQ AS L1
ON  L1.COD_CAMPAIGN=R.COD_CAMPAIGN
AND L1.COD_REPORT=R.COD_REPORT
AND L1.TABLE_NUM=R.TABLE_NUM
AND L1.LINE_NUM=R.LINE_NUM
AND L1.COD_LANG='en'
LEFT OUTER JOIN CM_LITERALS_IQ AS L2
ON  L2.COD_CAMPAIGN=R.COD_CAMPAIGN
AND L2.COD_REPORT=R.COD_REPORT
AND L2.TABLE_NUM=R.TABLE_NUM
AND L2.LINE_NUM=R.LINE_NUM
AND L2.COD_LANG='el'
LEFT OUTER JOIN CM_LITERALS_IQ AS L3
ON  L3.COD_CAMPAIGN=R.COD_CAMPAIGN
AND L3.COD_REPORT=R.COD_REPORT
AND L3.TABLE_NUM=R.TABLE_NUM
AND L3.CATEG_NUM=L1.CATEG_NUM
AND L3.COD_LANG=L1.COD_LANG
AND L3.LINE_NUM=0
LEFT OUTER JOIN CM_LITERALS_IQ AS L4
ON  L4.COD_CAMPAIGN=R.COD_CAMPAIGN
AND L4.COD_REPORT=R.COD_REPORT
AND L4.TABLE_NUM=R.TABLE_NUM
AND L4.CATEG_NUM=L2.CATEG_NUM
AND L4.COD_LANG=L2.COD_LANG
AND L4.LINE_NUM=0
WHERE
R.COD_CAMPAIGN='MDSHBRD10'
AND R.COD_REPORT=1
AND R.TABLE_NUM=1
AND R.COLUMN_NUM=6
AND R.COD_KPI IN
(
'DHSMLMPRD',
'DHNMLMPRD',
'DHNPIMPRD',
'DHNHIMPRD',
'DHNHEMPRD',
'DHSMFMPRD',
'DHSBIMPRD',
'DHNBSMPRD',
'DHNBLMPRD',
'DHNSBMPRD',
'DHNVBMPRD',
'DHNEPMPRD',
'DHSCLMPRD',
'DHNCLMPRD',
'DHNBTMPRD',
'DHNCVMPRD',
'DHNDCMPRD',
'DHNEIMPRD',
'DHNSOMPRD',
'DHNBPMPRD',
'DHNCNMPRD',
'DHNCTMPRD'
)

