SELECT SUM(BGT_KPI_VAL)
FROM cm_unit_budget_campaign_kpi_iq
WHERE COD_KPI LIKE '%DSNMLWPRD%'
AND UNIT_ID = 'KAT0001'
AND TIME_KEY_FROM >= 'W200901'
AND TIME_KEY_TO <= 'W200905'
ORDER BY TIME_KEY_FROM, TIME_KEY_TO


SELECT SUM(BGT_KPI_VAL)
FROM cm_unit_budget_campaign_kpi_iq
WHERE COD_KPI LIKE '%DSNMLYPRD%'
AND UNIT_ID = 'KAT0001'
AND TIME_KEY_FROM = 'W200905'
AND TIME_KEY_TO = 'W200905'
ORDER BY TIME_KEY_FROM, TIME_KEY_TO

INSERT INTO cm_kpi_iq
SELECT *
FROM cm_kpi_iq
WHERE COD_KPI LIKE '%DSNMLYRxx%'

SELECT DISTINCT TIME_KEY
FROM cm_msr_fact_iq

SELECT *
FROM cm_unit_budget_campaign_kpi_iq
WHERE COD_KPI LIKE '%DSNMLYPRD%'
AND TIME_KEY_FROM = 'W200947'
ORDER BY UNIT_ID

SELECT *
FROM cm_kpi_iq
WHERE COD_KPI LIKE '%DSNMLYRxx%'

INSERT INTO cm_kpi_iq
VALUES (
'DSNMLYBGT',
'Number of Mortgage Loans BGT (Ytd)',
'WCY',
'SUM',
'',
'BGT',
'DSNMLWPRD',
'',
'NBA',
'SUM',
1,
'SAVAS TEST',
''
)

INSERT INTO cm_campaign_kpi_iq
VALUES (
'WDSHBRD01',
'DSNMLYBGT'
)

SELECT *
FROM CM_CAMPAIGN_KPI_IQ

SELECT *
FROM cm_repdef_columns_iq
WHERE COD_KPI LIKE '%DSNMLY%'

UPDATE cm_repdef_columns_iq
SET COD_KPI='DSNMLYBGT',KPI_VALUE='BGT'
WHERE COD_KPI='DSNMLYPRD' AND KPI_VALUE='BVA'


